import turtle

def quadrados(lado, valor, base_case):
    if lado >= base_case:
        turtle.pencolor(1, 0, 0)
        for _ in range(4):
            turtle.forward(lado)
            turtle.left(90)
        turtle.penup()
        turtle.forward(-lado / valor / 2)
        turtle.right(90)
        turtle.forward(lado / valor / 2)
        turtle.left(90)
        turtle.pendown()
        quadrados(lado / valor, valor, base_case)
        turtle.penup()
        turtle.forward(lado)
        turtle.pendown()
        quadrados(lado / valor, valor, base_case)
        turtle.penup()
        turtle.left(90)
        turtle.forward(lado)
        turtle.right(90)
        turtle.pendown()
        quadrados(lado / valor, valor, base_case)
        turtle.penup()
        turtle.forward(-lado)
        turtle.pendown()
        quadrados(lado / valor, valor, base_case)
        turtle.penup()
        turtle.right(90)
        turtle.forward(lado - lado / valor / 2)
        turtle.left(90)
        turtle.forward(lado / valor / 2)
        turtle.pendown()

turtle.bgcolor("black")
turtle.speed(0.2)  
turtle.hideturtle()
turtle.penup()  
turtle.goto(0, 0)
turtle.pendown() 

turtle.left(90)
quadrados(200, 2, 10)
turtle.done() 
